### ISSUE TITLE
Official command to remove the apt news spam

### ISSUE THREAD

**Issue by bfontaine** [Skyedra/UnspamifyUbuntu#1]
(found via [this answer](https://askubuntu.com/a/1457810/207702))
Surprisingly, there is an official (but undocumented) way to disable the apt news spam:

    sudo pro config set apt_news=false

**Comment by Skyedra** [comment]
Yeah, they begrudgingly added this flag a month _after_ adding the spam, heh 🤦

Personally, I think they'll add more spam over time to the Advantage package and if people keep Advantage installed, there will be more flags to set to disable, resulting in a whack-a-mole approach.  But, I do think this is worth including as some people might need to use Advantage for the long term support, so I've updated the page.  

Thanks for the suggestion!
