### ISSUE TITLE
Ubuntu 22.04 update-manager needs patch / not compatible with Unspamify

### ISSUE THREAD

**Issue by reneas** [Skyedra/UnspamifyUbuntu#10]
I installed  `fake-ubuntu-advantage-tools` and everything is working fine, no Ubuntu Pro ads showing anymore.
Problem is now: I can't open the Software Update Settings neither from the update dialogue nor from the menu .
If I press on the button "Einstellungen" (Settings in German" in the following window it will only show a loading icon for a second and then return to the update window without opening any settings.
![image](https://github.com/Skyedra/UnspamifyUbuntu/assets/28440614/b492a3e0-b7ef-4c26-9b84-17492bbad1fa)

Also after finishing the update I can't access the settings through the button shown there:
![image](https://github.com/Skyedra/UnspamifyUbuntu/assets/28440614/531d6203-0fc6-433b-8395-693dee7a57fc)

I am running Ubuntu 22.04.3 LTS with GNOME 42.9 on a Lenovo ThinkPad L13 Yoga.

**Comment by Skyedra** [comment]
Hmm, looks like this is `update-manager` program maybe?  Did you do the "Patch Update Manager (for Ubuntu 23.04+ Desktop only)" section of instructions?

I actually just do updates via command line myself heh so I haven't tried this part much

**Comment by Skyedra** [comment]
Hmmm, I have not tried it before, so proceed with caution.  I would suggest backing up the affected files from that section first.  Then, if the dry run check (first step) does not cleanly apply, then do not proceed to the second step.  Good luck and let us know how it goes :)

**Comment by reneas** [comment]
okay so first it had issues, because the file is `read-only`. after runnig it with `sudo` I got the following error message:

```
checking file /usr/lib/python3/dist-packages/UpdateManager/UpdateManager.py
Hunk #1 FAILED at 44.
Hunk #2 FAILED at 278.
2 out of 3 hunks FAILED
```

Guess I shouldn't proceed with the patch :cry: 

Maybe its just fine, that I can't access the Preferences GUI and I'll be fine with the command line. Was just noticing this and thought I better tell you guys

**Comment by Skyedra** [comment]
Correct, definitely don't proceed as is :sweat_smile: 

Someone will need to write a patch for the 22.04 version (if you end up trying this, definitely send it along! ;))

For now, I will update the issue title and leave it open, since it would be nice for this project to be able to support this in 22.04 given it will still be LTS supported until April 2027.  Thanks for the report, though!

**Comment by reneas** [comment]
Unfortunately I think fixing this issue is way out of my league, so I'll have to pass and let someone else do the hard work :)

**Comment by reneas** [comment]
Okay sorry for the back and forth but after thinking about it, maybe changing the contents of `/usr/lib/python3/dist-packages/softwareproperties/gtk/SoftwarePropertiesGtk.py` and stopping it from calling for any kind of Ubuntu Pro related library or function would be the better way?
I'm new to Python but I'm gonna try to find a solution, no promises made though!

**Comment by reneas** [comment]
okay final comment on this :rofl: 

after commenting the following lines it works again!


line 57: 
```
from .UbuntuProPage import UbuntuProPage
```


line 254:
```
self.init_ubuntu_pro()
```


lines 1660 & 1661: 
```
def init_ubuntu_pro(self):
        self.ubuntu_pro_page = UbuntuProPage(self)
```

maybe there is some way of implementing this into the package?

**Comment by Skyedra** [comment]
Neat!  If you want to put that together as a [.patch file](https://www.howtogeek.com/415442/how-to-apply-a-patch-to-a-file-and-create-patches-in-linux/) like the other one, I'll add it to the instructions :)

**Comment by reneas** [comment]
I'll look into it tomorrow, thanks for the instructions :)

**Comment by reneas** [comment]
okay so i saw that there is already an open pull request #6 where the required path files are pretty much already there. i still made two new ones, which solve the issue by

1. deactivating `ubuntu pro` features in the `/usr/lib/python3/dist-packages/softwareproperties/gtk/SoftwarePropertiesGtk.py` with this patch file:

[SoftwarePropertiesGtk.patch.txt](https://github.com/Skyedra/UnspamifyUbuntu/files/14082653/SoftwarePropertiesGtk.patch.txt)

and 2. deleting the whole ubuntu pro tab in `/usr/share/software-properties/gtkbuilder/main.ui` with this patch file:

[main.patch.txt](https://github.com/Skyedra/UnspamifyUbuntu/files/14082663/main.patch.txt)


unfortunately github told me that it doesn't support the file type although `*.patch` files are in the list of supported file types so i uploaded them as `.txt`.

with this setup i have no problems with ubuntu pro anywhere. so maybe we can merge this issue and #6 and close them after adding the files to the repo?

**Comment by Skyedra** [comment]
Cool, yeah I didn't realize that older patch only worked on 22.04.  So now that I understand that, I went ahead and approved it and updated the docs.

I'm using the originally supplied patch because:
- In theory, diffs with context (the unchanging lines around the changed lines) should be a bit more safe to apply as less chance of it going into the wrong place.  Ie if upstream ubuntu changes something, it should throw a loud warning first
- Simpler to apply as it's one unified file

If the separated files does anything the earlier single file does not, please let me know.  Regardless, thanks for the additional information as it did help :)
