### ISSUE TITLE
Prevent APT trying to start spammy uninstalled services -> also for 22.04

### ISSUE THREAD

**Issue by Metrax** [Skyedra/UnspamifyUbuntu#7]
"(Ubuntu 23.04+ only) Prevent APT trying to start spammy uninstalled services"

Meanwhile this point is also required for 22.04:
```
root@jump:~# sudo apt-get update
Failed to start apt-news.service: Unit apt-news.service not found.
Failed to start esm-cache.service: Unit esm-cache.service not found.
root@jump:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

Steps to reproduce:
Fresh installation
apt update && apt dist-upgrade -y
apply UnspamifyUbuntu
apt update

Tested with manual and automatic installation.

Please remove the "(Ubuntu 23.04+ only)" :-)

**Comment by Skyedra** [comment]
Fixed, thanks for letting me know!
